### ISSUE TITLE
Persistent across reboots?

### ISSUE THREAD

**Issue by kasindhu** [izer-xyz/3cx-docker#10]
Hi, 

How do I keep this persistent once the 1st docker is run? additionally ports 9000-10999 also need to be exposed. Haven't been able to get this compiled with docker-compose either

**Comment by sinegar** [comment]
The volumes are not persisted but should survive a host reboot. You should run a scheduled backup to ensure no data is lost. 

It’s use at your own risk as the current version of 3cx is not designed for containers. ( I have been running it like this for quite some time. However, I only use a limited set of functionalities)
