### ISSUE TITLE
Can't start the web interface on 5015

### ISSUE THREAD

**Issue by thayoz** [izer-xyz/3cx-docker#11]
Hello while starting the container, nothing comes up...

> First run. Configure instance ...
> Check config tool logs in case of any issues /var/lib/3cxpbx/Data/Logs/PbxConfigTool.log
> Run WebConfig on port :5015
> Created symlink /etc/systemd/system/multi-user.target.wants/setup-3cx.service -> /etc/systemd/system/setup-3cx.service.
> chown: invalid user: 'phonesystem:phonesystem'

At the end of the init-3cx.sh:

chown phonesystem:phonesystem /run/phonesystem

This might be related ? User not created at docker creation ?

**Comment by sinegar** [comment]
That looks okay but `systemd` has issues on some hosts.  E.g. #4, #9 - neither were fixed as I couldn’t reproduce / host related issue. 

Few questions:
 * what do you see on the console after `chown`?
 * what environment do you use ? `docker info`
 * how do you start the container? And which image do you use?
 * what’s in the `/var/lib/3cxpbx/Data/Logs/PbxConfigTool.log` log file?
 * this might give more info on what’s wrong with systemd
    `docker run -it --rm --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro ghcr.io/izer-xyz/3cx:latest /lib/systemd/systemd --log-level=debug --log-target=console --show-status=true`

**Comment by sinegar** [comment]
Closing all issues before archiving the project.
