### ISSUE TITLE
Issues with first boot

### ISSUE THREAD

**Issue by jonatan-holmgren** [izer-xyz/3cx-docker#16]
```
Failed to create /init.scope control group: No such file or directory
Failed to allocate manager object: No such file or directory
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
```
What do I do?

**Comment by sinegar** [comment]
That looks like a problem with systemd. Have you mounted cgroup ( `-v    /sys/fs/cgroup:/sys/fs/cgroup:ro `)?

How do you start the container? Would you share the docker run command line or the docker compose file?

You can have a look at the readme Troubleshooting/ 1.

**Comment by etam** [comment]
duplicate of #4 ?

**Comment by sinegar** [comment]
Yes, it seems like a systemd issue which I can’t help.

**Comment by sinegar** [comment]
I had a similar issue with the github action that I use to build the container and adding `--cgroupns=host -v /sys/fs/cgroup:/sys/fs/cgroup:rw` to the command line. `cgroupns` might not work with docker compose.

**Comment by jonatan-holmgren** [comment]
Worked, closing.
