### ISSUE TITLE
Can't reach on 5001

### ISSUE THREAD

**Issue by MikroT** [izer-xyz/3cx-docker#19]
Hi

I configure docker compose as you suggest and i have done first configuration on 5015 port.

After all i see that i can't reach login or webclient on 5001 or 5000.

I try to enter in docker container and i see that services are disabled, i use this commands for test.

systemctl is-enabled 3CXIVR01.service
systemctl is-enabled 3CXPhoneSystem01.service
systemctl is-enabled 3CXMediaServer.service
systemctl is-enabled 3CXCallFlow01.service
systemctl is-enabled 3CXFirewall.service
systemctl is-enabled 3CXAudioProvider01.service
systemctl is-enabled 3CXCfgServ01.service
systemctl is-enabled 3CXEventNotificationManager.service
systemctl is-enabled 3CXSystemService01.service
systemctl is-enabled 3CXGatewayService.service
systemctl is-enabled 3CXPhoneSystemMC01.service
systemctl is-enabled 3CXQueueManager01.service
systemctl is-enabled nginx.service

next, i use this for enable services 

systemctl enable 3CXIVR01.service
systemctl enable 3CXPhoneSystem01.service
systemctl enable 3CXMediaServer.service
systemctl enable 3CXCallFlow01.service
systemctl enable 3CXFirewall.service
systemctl enable 3CXAudioProvider01.service
systemctl enable 3CXCfgServ01.service
systemctl enable 3CXEventNotificationManager.service
systemctl enable 3CXSystemService01.service
systemctl enable 3CXGatewayService.service
systemctl enable 3CXPhoneSystemMC01.service
systemctl enable 3CXQueueManager01.service
systemctl enable nginx

services seems now ENABLED but the webclient is not reached again
So i try to launch this command for status

systemctl status 3CXIVR01.service
systemctl status 3CXPhoneSystem01.service
systemctl status 3CXMediaServer.service
systemctl status 3CXCallFlow01.service
systemctl status 3CXFirewall.service
systemctl status 3CXAudioProvider01.service
systemctl status 3CXCfgServ01.service
systemctl status 3CXEventNotificationManager.service
systemctl status 3CXSystemService01.service
systemctl status 3CXGatewayService.service
systemctl status 3CXPhoneSystemMC01.service
systemctl status 3CXQueueManager01.service
systemctl status nginx.service

all services gain error except nginx, as you see:

root@dockerid:/# systemctl status 3CXIVR01.service
* 3CXIVR01.service - 3CX PhoneSystem 01 IVR Server
   Loaded: loaded (/lib/systemd/system/3CXIVR01.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
root@dockerid:/# systemctl status 3CXPhoneSystem01.service
* 3CXPhoneSystem01.service - 3CX PhoneSystem 01 SIP Server
   Loaded: loaded (/lib/systemd/system/3CXPhoneSystem01.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
root@dockerid:/# systemctl status 3CXMediaServer.service
* 3CXMediaServer.service - 3CX PhoneSystem Media Server
   Loaded: loaded (/lib/systemd/system/3CXMediaServer.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
root@dockerid:/# systemctl status 3CXCallFlow01.service
* 3CXCallFlow01.service - 3CX PhoneSystem 01 CallFlow Server
   Loaded: loaded (/lib/systemd/system/3CXCallFlow01.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
root@dockerid:/# systemctl status 3CXFirewall.service
* 3CXFirewall.service - 3CX PhoneSystem Firewall
   Loaded: loaded (/lib/systemd/system/3CXFirewall.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
root@dockerid:/# systemctl status 3CXAudioProvider01.service
* 3CXAudioProvider01.service - 3CX PhoneSystem 01 Audio Provider Server
   Loaded: loaded (/lib/systemd/system/3CXAudioProvider01.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
root@dockerid:/# systemctl status 3CXCfgServ01.service
* 3CXCfgServ01.service - 3CX PhoneSystem Configuration Service
   Loaded: loaded (/lib/systemd/system/3CXCfgServ01.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
root@dockerid:/# systemctl status 3CXEventNotificationManager.service
* 3CXEventNotificationManager.service - 3CX Event Notification Manager
   Loaded: loaded (/lib/systemd/system/3CXEventNotificationManager.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
root@dockerid:/# systemctl status 3CXSystemService01.service
* 3CXSystemService01.service - 3CX PhoneSystem 01 System Server
   Loaded: loaded (/lib/systemd/system/3CXSystemService01.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
root@dockerid:/# systemctl status 3CXGatewayService.service
* 3CXGatewayService.service - 3CX Gateway Service
   Loaded: loaded (/lib/systemd/system/3CXGatewayService.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
root@dockerid:/# systemctl status 3CXPhoneSystemMC01.service
* 3CXPhoneSystemMC01.service - 3CX PhoneSystem 01 Management Console
   Loaded: loaded (/lib/systemd/system/3CXPhoneSystemMC01.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
root@dockerid:/# systemctl status 3CXQueueManager01.service
* 3CXQueueManager01.service - 3CX PhoneSystem 01 Queue Manager Server
   Loaded: loaded (/lib/systemd/system/3CXQueueManager01.service; enabled; vendor preset: enabled)
   Active: inactive (dead)

so i try to start it manually by:

systemctl start 3CXIVR01.service
systemctl start 3CXPhoneSystem01.service
systemctl start 3CXMediaServer.service
systemctl start 3CXCallFlow01.service
systemctl start 3CXFirewall.service
systemctl start 3CXAudioProvider01.service
systemctl start 3CXCfgServ01.service
systemctl start 3CXEventNotificationManager.service
systemctl start 3CXSystemService01.service
systemctl start 3CXGatewayService.service
systemctl start 3CXPhoneSystemMC01.service
systemctl start 3CXQueueManager01.service
systemctl start nginx.service

but i get error on all services:

root@dockerid:/# systemctl start 3CXIVR01.service
A dependency job for 3CXIVR01.service failed. See 'journalctl -xe' for details.
root@dockerid:/# systemctl start 3CXPhoneSystem01.service
A dependency job for 3CXPhoneSystem01.service failed. See 'journalctl -xe' for details.
root@dockerid:/# systemctl start 3CXMediaServer.service
root@dockerid:/# systemctl start 3CXCallFlow01.service
A dependency job for 3CXCallFlow01.service failed. See 'journalctl -xe' for details.
root@dockerid:/# systemctl start 3CXFirewall.service
Job for 3CXFirewall.service failed because the control process exited with error code.
See "systemctl status 3CXFirewall.service" and "journalctl -xe" for details.
root@dockerid:/# systemctl start 3CXAudioProvider01.service
A dependency job for 3CXAudioProvider01.service failed. See 'journalctl -xe' for details.
root@dockerid:/# systemctl start 3CXCfgServ01.service
Job for 3CXCfgServ01.service failed because the service did not take the steps required by its unit configuration.
See "systemctl status 3CXCfgServ01.service" and "journalctl -xe" for details.
root@dockerid:/# systemctl start 3CXEventNotificationManager.service
root@dockerid:/# systemctl start 3CXSystemService01.service
A dependency job for 3CXSystemService01.service failed. See 'journalctl -xe' for details.
root@dockerid:/# systemctl start 3CXGatewayService.service
A dependency job for 3CXGatewayService.service failed. See 'journalctl -xe' for details.
root@dockerid:/# systemctl start 3CXPhoneSystemMC01.service
A dependency job for 3CXPhoneSystemMC01.service failed. See 'journalctl -xe' for details.
root@dockerid:/# systemctl start 3CXQueueManager01.service
A dependency job for 3CXQueueManager01.service failed. See 'journalctl -xe' for details.

This is console after 3cx server start:

test-container | First run. Configure instance ...
test-container | Check config tool logs in case of any issues /var/lib/3cxpbx/Data/Logs/PbxConfigTool.log
test-container | Run WebConfig on port :5015
test-container | Created symlink /etc/systemd/system/multi-user.target.wants/setup-3cx.service -> /etc/systemd/system/setup-3cx.service.
test-container | Start systemd
test-container | 
test-container | Welcome to Debian GNU/Linux 10 (buster)!
test-container | 
test-container | [  OK  ] Started Dispatch Password...s to Console Directory Watch.
test-container | [  OK  ] Reached target Network is Online.
test-container | [  OK  ] Reached target Swap.
test-container | [  OK  ] Reached target Local File Systems.
test-container | [  OK  ] Reached target Slices.
test-container | [  OK  ] Listening on Journal Socket (/dev/log).
test-container | [  OK  ] Reached target Paths.
test-container | [  OK  ] Listening on Journal Socket.
test-container |          Starting Create System Users...
test-container | [  OK  ] Reached target Local Encrypted Volumes.
test-container |          Starting Journal Service...
test-container | [  OK  ] Reached target Sockets.
test-container | [  OK  ] Started Create System Users.
test-container | [  OK  ] Started Journal Service.
test-container | [  OK  ] Reached target System Initialization.
test-container | [  OK  ] Started Daily Cleanup of Temporary Directories.
test-container | [  OK  ] Reached target Timers.
test-container | [  OK  ] Reached target Basic System.
test-container |          Starting A high performan...and a reverse proxy server...
test-container |          Starting Setup 3CX...
test-container |          Starting Flush Journal to Persistent Storage...
test-container | [  OK  ] Started Flush Journal to Persistent Storage.
test-container | [  OK  ] Created slice system-postgresql.slice.
test-container |          Starting PostgreSQL Cluster 11-main...
test-container | [  OK  ] Started A high performanc...r and a reverse proxy server.
test-container | [  OK  ] Started PostgreSQL Cluster 11-main.
test-container |          Starting PostgreSQL RDBMS...
test-container | [  OK  ] Started PostgreSQL RDBMS.
test-container | [  OK  ] Started Setup 3CX.
test-container | [  OK  ] Reached target Multi-User System.
test-container | [  OK  ] Reached target Graphical Interface.

Where i'm wrong?

**Comment by sinegar** [comment]
You should look for errors in the `/var/lib/3cxpbx/Data/Logs/PbxConfigTool.log` after the initial config on port 5015 (make sure not to change the default ports or if you do adjust the port mappings in the compose file). 

Also the port 5015 should be closed after a successful config.

**Comment by sinegar** [comment]
Closing all issues before archiving the project.
