### ISSUE TITLE
Persistant Volume

### ISSUE THREAD

**Issue by ClepToManix** [izer-xyz/3cx-docker#6]
Hey,

i tried to install your Docker-Container with Compose and Traefik-Setup.
Inside the Dockerfile only one volume is exposed. I dont know if this is correct, but im not able to stop the container and start it again with my configured instance. A reconfigure is needed. Maybe there is a need to define a volume, which holds the configuration data. 
But maybe im wrong and i use the wrong configuration. The volume voip only binds /mnt/voip inside the container.

**Comment by sinegar** [comment]
Are you stoping the container with `docker stop XXX` or `docker-compose down` or `docker-compose stop`?

Please note, `docker-compose up/down` create/destroy the container. `stop/start` should keep the container data. 

The persistent volume (`/mnt/voip`) in  the example is only used for backups.  The data/state is actually stored under `/var/lib/3cxpbx` but persisting as a volume would likely cause issues with upgrades (and also breaks the setup process, as the first run assumes the folder is not there). 

The [simple automated upgrade](https://github.com/izer-xyz/3cx-docker#automated--simple) process could automatically restore from backups. Please note, there is a rate limit (5 per week?) on certificate requests from 3cx.

**Comment by ClepToManix** [comment]
okay, maybe thats the problem. I stopped it with `docker-compose down` -.-
thanks for your fast answear 👍
